INSERT INTO Country(Country_Id,Country_Name) VALUES ('ALG','Algeria');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ANT','Antigua and Barbuda');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ARG','Argentina');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ARM','Armenia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('AUS','Australia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('AUT','Austria');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('AZE','Azerbaijan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BAH','Bahamas');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BAR','Barbados');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BDI','Burundi');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BEL','Belgium');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BIH','Bosnia and Herzegovina');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BLR','Belarus');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BOT','Botswana');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BRA','Brazil');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BRN','Bahrain');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BRU','Brunei');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('BUL','Bulgeria');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CAF','Central African Republic');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CAN','Canada');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CGO','Congo');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CHI','Chile');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CHN','China');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CIV','Ivory Coast');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CMR','Cameroon');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('COL','Colombia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CRC','Costa Rica');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CRO','Croatia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CUB','Cuba');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('CZE','Czech Repubic');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('DEN','Denmark');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('DOM','Dominican Republic');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ECU','Ecuador');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('EGY','Egypt');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ERI','Eritrea');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ESP','Spain');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('EST','Estonia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ETH','Ethiopia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('FIJ','Fiji');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('FIN','Finland');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('FRA','France');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('FSM','Federated States of Micronesia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GBR','Great Britain');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GEO','Georgia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GER','Germany');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GRE','Greece');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GRN','Grenada');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GUA','Guatemala');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('GUY','Guyana');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('HKG','Hong Kong');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('HON','Honduras');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('HUN','Hungary');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('INA','Indonesia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('IND','India');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('IRI','Iran');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('IRL','Ireland');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('IRQ','Iraq');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ISR','Israel');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ITA','Italy');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('JAM','Jamaica');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('JPN','Japan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('KAZ','Kazakhstan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('KEN','Kenya');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('KGZ','Kyrgyzstan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('KOR','Korea');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('LAT','Latvia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('LCA','Saint Lucia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('LIE','Liechtenstein');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('LTU','Lithuania');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('LUX','Luxembuorg');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MAR','Morocco');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MAS','Malasiya');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MDA','Moldova');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MEX','Mexico');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MGL','Mongolia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MNE','Montenegro');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('MRI','Mauritius');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('NED','Netherland');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('NGR','Nigeria');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('NOR','Norway');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('NZL','New Zealand');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('PAN','Panama');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('PAR','Paraguay');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('POL','Poland');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('POR','Portugal');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('PUR','Puerto Rico');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('QAT','Qatar');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ROU','Romania');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('RSA','South Africa');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('RUS','Russia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('RWA','Rwanda');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SIN','Singapore');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SKN','Saint Kitts and Nevis');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SLO','Slovakia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SRB','Serbia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SRI','Srilanka');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SUI','Swizerland');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SUR','Suriname');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SVK','Slovakia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('SWE','Sweden');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('THA','Thailand');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('TJK','Tajikistan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('TPE','Chinese Taipei');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('TTO','Trinidad and Tobago');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('TUN','Tunisia');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('TUR','Turkey');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('UAE','United Arab Emirates');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('UGA','Uganda');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('UKR','Ukraine');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('URU','Uruguay');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('USA','United States of America');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('UZB','Uzbekistan');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('VEN','Venezuela');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('VIE','Vietnam');
INSERT INTO Country(Country_Id,Country_Name) VALUES ('ZIM','Zimbabwe');
