INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E01','Women''s High Jump','Individual','Female','Jumps','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E02','Women''s Long Jump','Individual','Female','Jumps','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E03','Men''s Pole Vault','Individual','Male','Jumps','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E04','Men''s Triple Jump','Individual','Male','Jumps','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E05','Women''s Discus Throw','Individual','Female','Throws','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E06','Women''s Hammer Throw','Individual','Female','Throws','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E07','Men''s Javelin Throw','Individual','Male','Throws','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E08','Men''s Shot Put','Individual','Male','Throws','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E09','Women''s 10,000m','Individual','Female','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E10','Women''s 100m Hurdles','Individual','Female','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E11','Women''s 5000m','Individual','Female','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E12','Men''s 100m','Individual','Male','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E13','Men''s 200m','Individual','Male','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E14','Men''s 3000m Steeplechase','Individual','Male','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E15','Men''s 4 x 100m Relay','Team','Male','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E16','Men''s 400m','Individual','Male','Track','S01');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E48','Women''s Doubles','Team','Female','Badminton','S02');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E49','Women''s Singles','Individual','Female','Badminton','S02');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E50','Men''s Doubles','Team','Male','Badminton','S02');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E51','Men''s Singles','Individual','Male','Badminton','S02');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E52','Mixed Doubles','Team','Mixed','Badminton','S02');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E53','Women''s Fly (48-51kg)','Individual','Female','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E54','Women''s Light (57-60kg)','Individual','Female','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E55','Women''s Middle (69-75kg)','Individual','Female','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E57','Men''s Fly (52kg)','Individual','Male','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E58','Men''s Heavy (91kg)','Individual','Male','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E59','Men''s Light (60kg)','Individual','Male','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E63','Men''s Middle (75kg)','Individual','Male','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E65','Men''s Welter (69kg)','Individual','Male','Boxing','S03');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E66','Women Football','Team','Female','Football','S04');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E67','Men Football','Team','Male','Football','S04');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E68','Women Hockey','Team','Female','Hockey','S05');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E69','Men Hockey','Team','Male','Hockey','S05');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E70','Women''s Doubles','Team','Female','Tennis','S06');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E71','Women''s Singles','Individual','Female','Tennis','S06');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E72','Men''s Doubles','Team','Male','Tennis','S06');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E73','Men''s Singles','Individual','Male','Tennis','S06');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E74','Mixed Doubles','Team','Mixed','Tennis','S06');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E75','Women Beach Volleyball','Team','Female','Beach Volleyball','S07');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E76','Men Beach Volleyball','Team','Male','Beach Volleyball','S07');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E77','Women Volleyball','Team','Female','Volleyball','S07');
INSERT INTO Event(Event_Id,Event_Name,Event_Type,Event_Sex,Discipline,Sport_Id) VALUES ('E78','Men Volleyball','Team','Male','Volleyball','S07');
