INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P173','9.81 s',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P181','9.89 s',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P172','9.91 s',3);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P178','9.93 s',4);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P167','9.94 s',5);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P163','9.96 s',6);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P164','10.04 s',7);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M09','P182','10.06 s',8);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P164','9.95 s',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P163','9.97 s',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P167','9.98 s',3);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P169','10.03 s',4);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P177','10.05 s',5);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P170','10.08 s',6);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P175','10.11 s',7);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M10','P166','10.23 s',8);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P173','9.86 s',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P172','9.92 s',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P182','10.01 s',3);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P176','10.02  s',4);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P180','10.05 s',5);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P168','10.12 s',6);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P159','10.13 s',7);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M11','P161','DQ',8);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P181','9.94 s',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P178','10.01 s',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P171','10.07 s',3);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P174','10.08 s',4);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P162','10.13 s',5);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P165','10.16 s',6);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P179','10.17 s',7);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M12','P160','DNS',8);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M13','P414','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M13','P418','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M14','P411','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M14','P410','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M15','P412','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M15','P417','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M16','P413','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M16','P415','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M17','P414','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M17','P411','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M18','P413','2',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M18','P412','0',2);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M19','P414','3',1);
INSERT INTO Player_Match(Match_Id,Player_Id,Score,Position) VALUES ('M19','P413','0',2);
