INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA5','37.27 s',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA6','37.60 s',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA2','37.64 s',3);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA3','37.90 s',4);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA4','37.98 s',5);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA1','38.41 s',6);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA7','DQ',7);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M08','TA8','DQ',8);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M20','TF15','2',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M20','TF16','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M21','TF23','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M21','TF20','1',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M22','TF25','2',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M22','TF17','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M23','TF26','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M23','TF19','4',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M24','TF15','6',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M24','TF20','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M25','TF25','0',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M25','TF19','2',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M26','TF20','2',2);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M26','TF25','3',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M27','TF15','1(5)',1);
INSERT INTO Team_Match(Match_Id,Team_Id,Score,Position) VALUES ('M27','TF19','1(4)',2);
